"use client";

import { useState, type FormEvent } from "react";
import { Download, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";
import { idCardDetails } from "@/lib/id-card-content";

type Employee = { employeeNumber: string; deviceCode: string | null; firstName: string; lastName: string; position: string | null; joiningDate: string | null; phone: string | null; profilePicture: string | null; profile: { bloodGroup: string | null } | null };

export function IdCardGenerator() {
  const [deviceCode, setDeviceCode] = useState(""); const [employee, setEmployee] = useState<Employee | null>(null); const [loading, setLoading] = useState(false); const [photoX, setPhotoX] = useState(50); const [photoY, setPhotoY] = useState(50); const toast = useToast();
  async function lookup(event: FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch(`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Could not find employee."); setEmployee(data.employee); setPhotoX(50); setPhotoY(50); } catch (error) { setEmployee(null); toast("error", error instanceof Error ? error.message : "Could not find employee."); } finally { setLoading(false); } }
  return <div className="space-y-6"><form onSubmit={lookup} className="flex max-w-xl gap-3"><Field label="Device ID"><Input value={deviceCode} onChange={(event) => setDeviceCode(event.target.value)} placeholder="Enter biometric Device ID" required /></Field><Button className="mt-6" type="submit" loading={loading}><Search className="h-4 w-4" /> Find employee</Button></form>{employee && <><div className="grid gap-6 lg:grid-cols-2"><CardSide title="Front" employee={employee} photoPosition={{ x: photoX, y: photoY }} front /><CardSide title="Back" employee={employee} /></div>{employee.profilePicture && <section className="max-w-[306px] space-y-3 rounded-xl border border-edge bg-tint p-4"><div><h2 className="text-sm font-semibold">Photo framing</h2><p className="mt-1 text-xs text-muted-foreground">Adjust the photo position for this card. The PDF uses the same framing.</p></div><Field label="Horizontal position"><Input type="range" min="0" max="100" value={photoX} onChange={(event) => setPhotoX(Number(event.target.value))} /></Field><Field label="Vertical position"><Input type="range" min="0" max="100" value={photoY} onChange={(event) => setPhotoY(Number(event.target.value))} /></Field></section>}<a href={`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}&format=pdf&photoX=${photoX}&photoY=${photoY}`}><Button><Download className="h-4 w-4" /> Download front and back PDF</Button></a></>}</div>;
}

function CardSide({ title, employee, front = false, photoPosition = { x: 50, y: 50 } }: { title: string; employee: Employee; front?: boolean; photoPosition?: { x: number; y: number } }) { return <section><h2 className="mb-3 text-sm font-semibold">{title}</h2><div className="relative mx-auto aspect-[591/1004] w-full max-w-[306px] overflow-hidden bg-white bg-cover bg-center shadow-lg" style={{ backgroundImage: `url(/id-cards/${front ? "1" : "2"}.png)` }}>{front && <><div className="absolute left-[28%] top-[23%] box-border h-[29.5%] w-[37%] overflow-hidden rounded-md border-[3px] border-[#ef7600] bg-white/30">{employee.profilePicture ? <img src={employee.profilePicture} alt={`${employee.firstName} ${employee.lastName}`} className="h-full w-full object-cover" style={{ objectPosition: `${photoPosition.x}% ${photoPosition.y}%` }} /> : <span className="flex h-full items-center justify-center text-[7px] font-semibold text-[#985016]">PHOTO</span>}</div><dl className="absolute left-[2%] top-[53.4%] w-[96%] space-y-[1.8%] font-bold leading-tight text-[#985016]" style={{ fontFamily: "Canva Sans, Arial, sans-serif", fontSize: "10pt" }}>{idCardDetails(employee).map(([label, value]) => <div key={label} className="grid grid-cols-[32%_68%]"><dt>{label}</dt><dd className="truncate" title={value}>: {value}</dd></div>)}</dl></>}</div></section>; }
