"use client";

import { useState, type FormEvent } from "react";
import { Download, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";

type Employee = { employeeNumber: string; deviceCode: string | null; firstName: string; lastName: string; position: string | null; joiningDate: string | null; phone: string | null; profilePicture: string | null; profile: { bloodGroup: string | null } | null };
const details = (employee: Employee) => [["Emp. ID", employee.deviceCode ?? employee.employeeNumber], ["Emp. Name", `${employee.firstName} ${employee.lastName}`], ["Designation", employee.position ?? "-"], ["DOJ", employee.joiningDate ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(employee.joiningDate)) : "-"], ["Blood Group", employee.profile?.bloodGroup ?? "-"], ["Contact", employee.phone ?? "-"]];

export function IdCardGenerator() {
  const [deviceCode, setDeviceCode] = useState(""); const [employee, setEmployee] = useState<Employee | null>(null); const [loading, setLoading] = useState(false); const toast = useToast();
  async function lookup(event: FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch(`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Could not find employee."); setEmployee(data.employee); } catch (error) { setEmployee(null); toast("error", error instanceof Error ? error.message : "Could not find employee."); } finally { setLoading(false); } }
  return <div className="space-y-6"><form onSubmit={lookup} className="flex max-w-xl gap-3"><Field label="Device ID"><Input value={deviceCode} onChange={(event) => setDeviceCode(event.target.value)} placeholder="Enter biometric Device ID" required /></Field><Button className="mt-6" type="submit" loading={loading}><Search className="h-4 w-4" /> Find employee</Button></form>{employee && <><div className="grid gap-6 lg:grid-cols-2"><CardSide title="Front" employee={employee} front /><CardSide title="Back" employee={employee} /></div><a href={`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}&format=pdf`}><Button><Download className="h-4 w-4" /> Download front and back PDF</Button></a></>}</div>;
}

function CardSide({ title, employee, front = false }: { title: string; employee: Employee; front?: boolean }) { return <section><h2 className="mb-3 text-sm font-semibold">{title}</h2><div className="relative mx-auto aspect-[591/1004] w-full max-w-[306px] overflow-hidden bg-white bg-cover bg-center shadow-lg" style={{ backgroundImage: `url(/id-cards/${front ? "1" : "2"}.png)` }}>{front && <><div className="absolute left-[28%] top-[23%] h-[29.5%] w-[37%] overflow-hidden rounded-md" style={{ border: "3px solid #ef7600" }}>{employee.profilePicture ? <img src={employee.profilePicture} alt={`${employee.firstName} ${employee.lastName}`} className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center bg-white/30 text-[7px] font-semibold text-[#985016]">PHOTO</span>}</div><dl className="absolute left-[2%] top-[53.4%] w-[96%] space-y-[1.8%] font-bold leading-tight text-[#985016]" style={{ fontFamily: "Canva Sans, Arial, sans-serif", fontSize: "7pt" }}>{details(employee).map(([label, value]) => <div key={label} className="grid grid-cols-[32%_68%]"><dt>{label}</dt><dd>: {value}</dd></div>)}</dl></>}</div></section>; }
