"use client";

import { useState, type FormEvent } from "react";
import { Download, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";

type Employee = { employeeNumber: string; deviceCode: string | null; firstName: string; lastName: string; position: string | null; joiningDate: string | null; phone: string | null; profilePicture: string | null; profile: { bloodGroup: string | null } | null };
const details = (employee: Employee) => [["Emp. ID", employee.deviceCode ?? employee.employeeNumber], ["Emp. Name", `${employee.firstName} ${employee.lastName}`], ["Designation", employee.position ?? "-"], ["DOJ", employee.joiningDate ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(employee.joiningDate)) : "-"], ["Blood Group", employee.profile?.bloodGroup ?? "-"], ["Contact", employee.phone ?? "-"]];

export function IdCardGenerator() {
  const [deviceCode, setDeviceCode] = useState(""); const [employee, setEmployee] = useState<Employee | null>(null); const [loading, setLoading] = useState(false); const toast = useToast();
  async function lookup(event: FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch(`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Could not find employee."); setEmployee(data.employee); } catch (error) { setEmployee(null); toast("error", error instanceof Error ? error.message : "Could not find employee."); } finally { setLoading(false); } }
  return <div className="space-y-6"><form onSubmit={lookup} className="flex max-w-xl gap-3"><Field label="Device ID"><Input value={deviceCode} onChange={(event) => setDeviceCode(event.target.value)} placeholder="Enter biometric Device ID" required /></Field><Button className="mt-6" type="submit" loading={loading}><Search className="h-4 w-4" /> Find employee</Button></form>{employee && <><div className="grid gap-6 lg:grid-cols-2"><CardSide title="Front" employee={employee} front /><CardSide title="Back" employee={employee} /></div><a href={`/api/id-cards?deviceCode=${encodeURIComponent(deviceCode.trim())}&format=pdf`}><Button><Download className="h-4 w-4" /> Download front and back PDF</Button></a></>}</div>;
}

function CardSide({ title, employee, front = false }: { title: string; employee: Employee; front?: boolean }) { return <section><h2 className="mb-3 text-sm font-semibold">{title}</h2><div className="mx-auto aspect-[153/244] w-full max-w-[306px] overflow-hidden bg-white p-4 text-[#985016] shadow-lg"><div className="text-center font-bold text-[#ef7600]">K</div><div className="mt-1 text-center text-sm font-bold">KEYSTONE INFRA PVT. LTD.</div>{front ? <><div className="mx-auto my-4 flex h-36 w-28 items-center justify-center overflow-hidden rounded-lg border-4 border-[#ef7600] bg-sky-100">{employee.profilePicture ? <img src={employee.profilePicture} alt={`${employee.firstName} ${employee.lastName}`} className="h-full w-full object-cover" /> : <span className="text-xs">PHOTO</span>}</div><dl className="space-y-1 text-xs font-bold">{details(employee).map(([label, value]) => <div key={label} className="grid grid-cols-[5rem_1fr]"><dt>{label}</dt><dd>: {value}</dd></div>)}</dl></> : <div className="mt-5 space-y-5 text-center text-xs font-bold leading-5"><p>This Identity Card Must Be Worn and prominently displayed by employee on duty and produced on demand by Security Staff Or Any Authorized Management representative</p><p>This Card Is Not Transferable. Misuse Of Any Kind Will Invite Disciplinary Action</p><p>Loss Of Card Must Be Immediately Intimated To Human Resource Dept</p><p>On Cessation Of Employment, employee must Return This Card To Human Resource Dept</p><p>If Found Please return This Card To:<br />KEYSTONE INFRA PVT. LTD.</p></div>}<div className="mt-4 border-t-4 border-[#ef7600] pt-2 text-center text-[10px]">H.No: 8-2-350/5/1, Road No-03,<br />Banjara Hills, Hyderabad, Telangana 500034<br />Phone: 9393645644<br />Email: hyd@keystoneinfra.com</div></div></section>; }
