"use client";

import { useState, type FormEvent } from "react";
import { CheckCircle2, Plus, Save, ShieldAlert } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useToast } from "@/components/ui/toast";

type Profile = { legalName?: string | null; logoUrl?: string | null; address?: string | null; contactName?: string | null; contactEmail?: string | null; contactPhone?: string | null; website?: string | null; taxId?: string | null; registrationNo?: string | null } | null;
type Location = { id: string; name: string; code: string; profile: { address?: string | null; contactName?: string | null; contactEmail?: string | null; contactPhone?: string | null; logoUrl?: string | null } | null };
type Record = { id: string; kind: string; version: number; active: boolean; effectiveFrom: Date; effectiveTo: Date | null; location: { name: string } | null };

export function ConfigurationManager({ tenant, locations, records }: { tenant: { name: string; email: string | null; phone: string | null; address: string | null; profile: Profile }; locations: Location[]; records: Record[] }) {
  const router = useRouter(); const toast = useToast(); const [busy, setBusy] = useState(false); const [locationId, setLocationId] = useState(locations[0]?.id ?? "");
  async function request(url: string, method: string, body: unknown) { const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.error ?? "Could not save configuration."); return data; }
  async function saveTenant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await request("/api/configuration", "PUT", { action: "tenant-profile", ...Object.fromEntries(form) }); toast("success", "Company profile saved"); router.refresh(); } catch (e) { toast("error", e instanceof Error ? e.message : "Could not save"); } finally { setBusy(false); } }
  async function saveLocation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!locationId) return; setBusy(true); const form = new FormData(event.currentTarget); try { await request("/api/configuration", "PUT", { action: "location-profile", locationId, ...Object.fromEntries(form) }); toast("success", "Location profile saved"); router.refresh(); } catch (e) { toast("error", e instanceof Error ? e.message : "Could not save"); } finally { setBusy(false); } }
  async function createRecord(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { const payload = JSON.parse(String(form.get("payload") || "{}")); await request("/api/configuration", "POST", { kind: form.get("kind"), locationId: form.get("scope") || null, effectiveFrom: form.get("effectiveFrom"), effectiveTo: form.get("effectiveTo") || null, payload }); toast("success", "Inactive configuration version created"); event.currentTarget.reset(); router.refresh(); } catch (e) { toast("error", e instanceof Error ? e.message : "Payload must be valid JSON"); } finally { setBusy(false); } }
  async function toggle(record: Record) { setBusy(true); try { await request("/api/configuration", "PATCH", { id: record.id, active: !record.active }); toast("success", record.active ? "Record marked inactive" : "Record marked active (not yet used by live features)"); router.refresh(); } catch (e) { toast("error", e instanceof Error ? e.message : "Could not update"); } finally { setBusy(false); } }
  const profile = tenant.profile;
  const selected = locations.find((location) => location.id === locationId);
  return <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Company master profile</CardTitle></CardHeader><CardContent><form onSubmit={saveTenant} className="grid gap-3 sm:grid-cols-2"><Field label="Company name"><Input name="legalName" defaultValue={profile?.legalName ?? tenant.name} required /></Field><Field label="Logo URL"><Input name="logoUrl" defaultValue={profile?.logoUrl ?? ""} /></Field><Field label="Contact name"><Input name="contactName" defaultValue={profile?.contactName ?? ""} /></Field><Field label="Contact email"><Input name="contactEmail" type="email" defaultValue={profile?.contactEmail ?? tenant.email ?? ""} /></Field><Field label="Contact phone"><Input name="contactPhone" defaultValue={profile?.contactPhone ?? tenant.phone ?? ""} /></Field><Field label="Website"><Input name="website" defaultValue={profile?.website ?? ""} /></Field><Field label="Tax ID"><Input name="taxId" defaultValue={profile?.taxId ?? ""} /></Field><Field label="Registration no."><Input name="registrationNo" defaultValue={profile?.registrationNo ?? ""} /></Field><Field label="Registered address" className="sm:col-span-2"><Input name="address" defaultValue={profile?.address ?? tenant.address ?? ""} /></Field><div className="sm:col-span-2 flex justify-end"><Button type="submit" loading={busy}><Save className="h-4 w-4" /> Save company profile</Button></div></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Location master profile</CardTitle></CardHeader><CardContent><div className="mb-4"><Select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Select a location</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name} ({location.code})</option>)}</Select></div>{selected ? <form onSubmit={saveLocation} className="grid gap-3 sm:grid-cols-2"><Field label="Address"><Input name="address" defaultValue={selected.profile?.address ?? ""} /></Field><Field label="Logo URL"><Input name="logoUrl" defaultValue={selected.profile?.logoUrl ?? ""} /></Field><Field label="Contact name"><Input name="contactName" defaultValue={selected.profile?.contactName ?? ""} /></Field><Field label="Contact email"><Input name="contactEmail" type="email" defaultValue={selected.profile?.contactEmail ?? ""} /></Field><Field label="Contact phone"><Input name="contactPhone" defaultValue={selected.profile?.contactPhone ?? ""} /></Field><div className="flex items-end justify-end"><Button type="submit" loading={busy}><Save className="h-4 w-4" /> Save location profile</Button></div></form> : <p className="text-sm text-muted-foreground">Create a location before adding a location profile.</p>}</CardContent></Card>
  <Card className="xl:col-span-2"><CardHeader><CardTitle>Versioned configuration drafts</CardTitle></CardHeader><CardContent><div className="mb-5 flex gap-3 rounded-xl border border-amber-400/20 bg-amber-500/5 p-3 text-[13px] text-muted-foreground"><ShieldAlert className="h-5 w-5 shrink-0 text-amber-500" />Tenant records are inherited by locations unless a location record is selected by a future consumer. Records are inactive by default. This release stores and audits them only: dashboard, ID cards, leave rules, and payroll calculations continue using their current settings.</div><form onSubmit={createRecord} className="grid gap-3 md:grid-cols-4"><Field label="Configuration"><Select name="kind" defaultValue="dashboard"><option value="dashboard">Dashboard</option><option value="id_card">ID-card template</option><option value="leave_policy">Leave policy</option><option value="payroll_policy">Payroll policy</option></Select></Field><Field label="Scope"><Select name="scope" defaultValue=""><option value="">Tenant-wide (inherited)</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name} override</option>)}</Select></Field><Field label="Effective from"><Input name="effectiveFrom" type="date" required /></Field><Field label="Effective to (optional)"><Input name="effectiveTo" type="date" /></Field><Field label="JSON payload" className="md:col-span-3"><textarea name="payload" required defaultValue="{}" className="min-h-11 w-full rounded-lg border border-input bg-background px-3 py-2 font-mono text-xs" /></Field><div className="flex items-end"><Button type="submit" loading={busy}><Plus className="h-4 w-4" /> Create vNext</Button></div></form><div className="mt-6 divide-y divide-edge rounded-xl border border-edge">{records.length === 0 ? <p className="p-4 text-sm text-muted-foreground">No draft configuration records yet.</p> : records.map((record) => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="text-sm font-semibold">{record.kind.replace("_", " ")} v{record.version} <span className={record.active ? "text-emerald-500" : "text-muted-foreground"}>{record.active ? "active" : "inactive"}</span></p><p className="text-xs text-muted-foreground">{record.location?.name ?? "Tenant-wide"} · effective {new Date(record.effectiveFrom).toLocaleDateString()}{record.effectiveTo ? ` to ${new Date(record.effectiveTo).toLocaleDateString()}` : ""}</p></div><Button size="sm" variant="outline" loading={busy} onClick={() => toggle(record)}><CheckCircle2 className="h-3.5 w-3.5" /> {record.active ? "Deactivate" : "Mark active"}</Button></div>)}</div></CardContent></Card></div>;
}
