"use client";

import { useState, type FormEvent } from "react";
import { ArrowRightLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input, Textarea } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { useToast } from "@/components/ui/toast";
import { useRouter } from "next/navigation";

type Option = { id: string; name: string };

export function EmployeeTransfer({ employeeId, employeeName, branches, departments, shifts, managers }: { employeeId: string; employeeName: string; branches: Option[]; departments: Option[]; shifts: Option[]; managers: Array<{ id: string; firstName: string; lastName: string; employeeNumber: string }> }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const toast = useToast(); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/transfers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId, destinationBranchId: form.get("destinationBranchId"), destinationDepartmentId: form.get("destinationDepartmentId") || null, destinationShiftId: form.get("destinationShiftId") || null, destinationManagerId: form.get("destinationManagerId") || null, destinationPosition: form.get("destinationPosition") || null, effectiveDate: form.get("effectiveDate"), reason: form.get("reason"), note: form.get("note") || null }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Could not schedule transfer."); toast("success", "Transfer scheduled"); setOpen(false); router.refresh(); } catch (error) { toast("error", error instanceof Error ? error.message : "Could not schedule transfer."); } finally { setSaving(false); } }
  return <><Button size="sm" variant="outline" onClick={() => setOpen(true)}><ArrowRightLeft className="h-3.5 w-3.5" /> Transfer</Button><Modal open={open} onClose={() => setOpen(false)} title={`Transfer ${employeeName}`} description="The current assignment is preserved. The move takes effect on the selected date."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Destination branch"><select name="destinationBranchId" required className="h-11 w-full rounded-[11px] border border-input bg-card px-3.5 text-sm"><option value="">Select branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field><Field label="Effective date"><Input name="effectiveDate" type="date" required /></Field><Field label="Destination department"><select name="destinationDepartmentId" className="h-11 w-full rounded-[11px] border border-input bg-card px-3.5 text-sm"><option value="">Keep current</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></Field><Field label="Destination shift"><select name="destinationShiftId" className="h-11 w-full rounded-[11px] border border-input bg-card px-3.5 text-sm"><option value="">Keep current</option>{shifts.map((shift) => <option key={shift.id} value={shift.id}>{shift.name}</option>)}</select></Field><Field label="Destination manager"><select name="destinationManagerId" className="h-11 w-full rounded-[11px] border border-input bg-card px-3.5 text-sm"><option value="">Keep current</option>{managers.filter((manager) => manager.id !== employeeId).map((manager) => <option key={manager.id} value={manager.id}>{manager.firstName} {manager.lastName} ({manager.employeeNumber})</option>)}</select></Field><Field label="Destination position"><Input name="destinationPosition" placeholder="Keep current if blank" /></Field><div className="sm:col-span-2"><Field label="Reason"><Input name="reason" required placeholder="Reason for transfer" /></Field></div><div className="sm:col-span-2"><Field label="Notes"><Textarea name="note" /></Field></div><div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" loading={saving}>Schedule transfer</Button></div></form></Modal></>;
}
