"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowRight, CheckCircle2, Download, FileArchive, FileSpreadsheet, Landmark, Play, Settings2, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge, StatusPill } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { formatMoney } from "@/lib/utils";
import { formatDate } from "@/lib/dates";
import { useToast } from "@/components/ui/toast";

type Employee = { id: string; employeeNumber: string; firstName: string; lastName: string; salary: number | null; accountNumber: string | null; ifscCode: string | null; department: { name: string } | null; branch: { name: string } | null };
type Payslip = { id: string; payrollRunId?: string | null; month: string; grossEarnings: number; deductions: number; netSalary: number; status: string; presentDays: number; lateDays: number; halfDays: number; absentDays: number; absentDeduction?: number; adjustments: { label: string; amount: number }[] | null; paidAt: string | Date | null };
type Row = { employee: Employee; payslip: Payslip | null };
type Run = { id: string; month: string; status: string; createdBy: string; createdAt: string | Date; reviewedAt?: string | Date | null; approvedAt?: string | Date | null; finalizedAt?: string | Date | null; paidAt?: string | Date | null; _count: { payslips: number; members?: number }; members?: { id: string; exception: string | null; employee: { id: string; employeeNumber: string; firstName: string; lastName: string } }[] };

const lifecycle = ["draft", "reviewed", "approved", "finalized", "paid"];
const labels: Record<string, string> = { draft: "Draft", reviewed: "Review", approved: "Approved", finalized: "Finalized", paid: "Paid" };

function person(employee: Pick<Employee, "firstName" | "lastName">) { return `${employee.firstName} ${employee.lastName}`.trim(); }

export function PayrollPanel({ month, locationLabel, locationId, locations, rows, totals, generated, canManageSettings, run, history, provenance }: { month: string; locationLabel: string; locationId: string | null; locations: { id: string; name: string }[]; rows: Row[]; totals: { gross: number; deductions: number; net: number; paid: number }; generated: number; canManageSettings: boolean; run: Run | null; history: Run[]; provenance: { version: number | null; location: string } | null }) {
  const router = useRouter();
  const toast = useToast();
  const [busy, setBusy] = useState<string | null>(null);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [detail, setDetail] = useState<Row | null>(null);
  const [bank, setBank] = useState("generic");
  const exceptionRows = [
    ...rows.filter(({ payslip }) => payslip && payslip.netSalary < 0).map(({ employee }) => ({ employee, message: "Negative net pay must be resolved before finalization." })),
    ...rows.filter(({ payslip, employee }) => payslip && (!employee.accountNumber || !employee.ifscCode)).map(({ employee }) => ({ employee, message: "Missing bank account or IFSC. This employee will be excluded from a bank export." })),
    ...(run?.members ?? []).filter((member) => member.exception).map((member) => ({ employee: member.employee, message: member.exception! })),
  ];

  function changeScope(nextMonth = month, nextLocation = locationId, nextRun?: string) { const query = new URLSearchParams({ period: nextMonth }); if (nextLocation) query.set("location", nextLocation); if (nextRun) query.set("run", nextRun); router.push(`/admin/payroll/process?${query}`); }
  async function createDraft() {
    setBusy("create");
    try {
      const response = await fetch("/api/payroll/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ month, locationId }) });
      const data = await response.json();
      if (!response.ok) return toast("error", data.error ?? "Could not create payroll draft.");
      toast("success", `Draft created: ${data.totals.created} payslips generated.`);
      changeScope(month, locationId, data.runId);
    } finally { setBusy(null); }
  }
  async function transition(status: string) {
    if (!run) return;
    setBusy(status);
    try {
      const payment = status === "paid" ? { paymentMethod: window.prompt("Payment method: cash, upi, bank, or other"), settlementDate: window.prompt("Settlement date (YYYY-MM-DD)"), paymentReference: window.prompt("Payment reference or batch ID"), confirmedCount: Number(window.prompt(`Confirm payslip count (${generated})`)), confirmedNet: Number(window.prompt(`Confirm net total (${totals.net.toFixed(2)})`)) } : {};
      const response = await fetch(`/api/payroll/runs/${run.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, ...payment }) });
      const data = await response.json();
      if (!response.ok) return toast("error", data.error ?? "Run transition failed.");
      toast("success", `Payroll run ${status}.`);
      router.refresh();
    } finally { setBusy(null); }
  }
  async function exportBank() {
    if (!run) return;
    setBusy("bank");
    try {
      const response = await fetch(`/api/payroll/export?${new URLSearchParams({ month, bank, runId: run.id }).toString()}`);
      if (!response.ok) { const data = await response.json().catch(() => ({})); return toast("error", data.error ?? "Bank export failed."); }
      const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `salary-${month}.csv`; link.click(); URL.revokeObjectURL(url);
      toast("success", "Bank file downloaded. Record payment only after the bank confirms settlement.");
    } finally { setBusy(null); }
  }
  function downloadSlip(row: Row) { if (row.payslip && run) window.location.href = `/api/payroll/payslips?${new URLSearchParams({ month, employeeIds: row.employee.id, runId: run.id })}`; }
  const next = !run ? { label: "Create draft run", copy: "Calculates this period using the policy in effect. It does not pay employees.", action: createDraft, key: "create" } : run.status === "draft" ? { label: "Send for review", copy: "Confirm exceptions and calculation inputs before sending this draft to a reviewer.", action: () => transition("reviewed"), key: "reviewed" } : run.status === "reviewed" ? { label: "Approve run", copy: run.createdBy ? "Approval is a separate control. The run creator cannot approve their own run." : "Approval is a separate control.", action: () => transition("approved"), key: "approved" } : run.status === "approved" ? { label: "Finalize payroll", copy: "Freezes payroll documents and enables the bank export after preflight passes.", action: () => transition("finalized"), key: "finalized" } : run.status === "finalized" ? { label: "Mark run paid", copy: "Use only after the payment batch has settled. This marks all run payslips paid.", action: () => transition("paid"), key: "paid" } : null;

  return <div className="min-w-0 payroll-process">
    <section className="border-b border-edge px-5 py-5 sm:px-6">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2"><Badge tone="success">Process payroll</Badge>{run && <StatusPill status={run.status} />}</div>
          <h2 className="mt-3 font-display text-xl font-semibold tracking-tight">Payroll management <span className="text-muted-foreground">/ {month}</span></h2>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">A controlled calculation and payout workflow for {locationLabel}. Statutory files remain unverified operational summaries.</p>
        </div>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:w-[25rem]">
          <label className="text-xs font-medium text-muted-foreground">Pay period<input aria-label="Payroll period" type="month" value={month} onChange={(event) => changeScope(event.target.value, locationId)} className="mt-1 h-11 w-full rounded-xl border border-input bg-card px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring" /></label>
          <label className="text-xs font-medium text-muted-foreground">Scope<select aria-label="Payroll location scope" value={locationId ?? ""} onChange={(event) => changeScope(month, event.target.value || null)} disabled={!canManageSettings} className="mt-1 h-11 w-full rounded-xl border border-input bg-tint px-3 text-sm text-foreground disabled:opacity-100"><option value="">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}{!canManageSettings && <option value={locationId ?? ""}>{locationLabel}</option>}</select></label>
          {canManageSettings && <Button variant="ghost" className="sm:col-span-2 justify-start" onClick={() => { window.location.href = "/admin/payroll/configuration"; }}><Settings2 aria-hidden="true" className="h-4 w-4" />Policy configuration</Button>}
        </div>
      </div>
      <section className="mt-5 grid gap-3 rounded-xl border border-emerald-300/40 bg-emerald-500/[0.06] p-4 sm:grid-cols-3" aria-label="Payroll configuration provenance"><div className="sm:col-span-3"><p className="text-sm font-semibold text-foreground">Configuration provenance</p><p className="mt-0.5 text-xs text-muted-foreground">{provenance ? `This selected run uses policy version ${provenance.version ?? 'recorded'} for ${provenance.location}.` : 'A configuration version will be recorded with each generated payslip.'}</p></div><ProcessTile label="Policy version" value={provenance?.version ? `Version ${provenance.version}` : 'Not generated'} tone="emerald" /><ProcessTile label="Effective period" value={run ? month : 'Select a period'} tone="blue" /><ProcessTile label="Operational scope" value={locationLabel} tone="violet" /></section>
      <Lifecycle status={run?.status} />
    </section>

    {next ? <section className="flex flex-col gap-3 border-b border-primary/20 bg-primary/[0.055] px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="text-sm font-semibold">Next control: {next.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{next.copy}</p></div><div className="flex gap-2"><Button className="w-full sm:w-auto" loading={busy === next.key} onClick={next.action}>{next.label}<ArrowRight aria-hidden="true" className="h-4 w-4" /></Button>{run && ["draft", "reviewed", "approved"].includes(run.status) && <Button variant="outline" loading={busy === "cancelled"} onClick={() => transition("cancelled")}>Cancel run</Button>}</div></section> : <section className="border-b border-edge bg-tint/40 px-5 py-4 text-sm text-muted-foreground">This run is terminal. Its records remain available for audit and document retrieval.</section>}

    {!run && <EmptyState canManageSettings={canManageSettings} />}
    {run && <>
      <section className="grid gap-px border-b border-edge bg-edge sm:grid-cols-2 lg:grid-cols-4">
        <Kpi label="Employees calculated" value={String(generated)} detail={`${rows.length - generated} not generated`} />
        <Kpi label="Gross earnings" value={formatMoney(totals.gross)} />
        <Kpi label="Deductions" value={formatMoney(totals.deductions)} />
        <Kpi label="Net pay" value={formatMoney(totals.net)} detail={run.status === "paid" ? `${totals.paid} paid` : "Not a payment confirmation"} prominent />
      </section>
      <section className="grid gap-4 border-b border-edge p-5 lg:grid-cols-[1.25fr_.75fr] sm:p-6">
        <div className="rounded-xl border border-edge bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Action required</h3><p className="text-xs text-muted-foreground">Resolve or acknowledge blockers before finalization.</p></div><Badge tone={exceptionRows.length ? "warning" : "success"}>{exceptionRows.length ? `${exceptionRows.length} items` : "Clear"}</Badge></div>{exceptionRows.length ? <ul className="mt-3 divide-y divide-edge">{exceptionRows.slice(0, 4).map((item, index) => <li key={`${item.employee.id}-${index}`} className="flex gap-3 py-3"><AlertTriangle aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><p className="text-sm"><button className="font-medium underline-offset-2 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => setDetail(rows.find((row) => row.employee.id === item.employee.id) ?? null)}>{person(item.employee)}</button><span className="block text-xs text-muted-foreground">{item.message}</span></p></li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">No calculation, member, or bank-detail exceptions found in this run.</p>}</div>
        <div className="rounded-xl border border-edge bg-tint/40 p-4"><h3 className="font-semibold">Run tools</h3><p className="mt-1 text-xs text-muted-foreground">Documents and exports are grouped away from lifecycle controls.</p><div className="mt-4 grid gap-2"><Button variant="outline" onClick={() => setReviewOpen(true)}><FileSpreadsheet aria-hidden="true" className="h-4 w-4" />Review run</Button>{(run.status === "finalized" || run.status === "paid") && <><div className="flex gap-2"><Select aria-label="Bank export format" value={bank} onChange={(event) => setBank(event.target.value)}><option value="generic">Generic NEFT</option><option value="hdfc">HDFC eNET</option><option value="icici">ICICI PAB-SAL</option></Select><Button variant="outline" loading={busy === "bank"} onClick={exportBank}><Landmark aria-hidden="true" className="h-4 w-4" />Bank file</Button></div><Button variant="outline" onClick={() => { window.location.href = `/api/payroll/runs/${run.id}/register`; }}><Download aria-hidden="true" className="h-4 w-4" />Payroll register CSV</Button></>}</div></div>
      </section>
      <Register rows={rows} onOpen={setDetail} />
      <History history={history} current={run.id} />
    </>}
    <section className="border-t border-amber-400/25 bg-amber-500/[0.06] px-5 py-3 sm:px-6"><div className="flex gap-2 text-xs text-amber-200"><ShieldAlert aria-hidden="true" className="h-4 w-4 shrink-0" /><p><strong>Compliance exports are unverified.</strong> PF, ESIC, TDS, Form 16, and 24Q downloads are calculation summaries only. Validate statutory rules and complete a client review before filing.</p></div></section>
    <ReviewModal open={reviewOpen} onClose={() => setReviewOpen(false)} run={run} rows={rows} totals={totals} onSlip={downloadSlip} />
    <EmployeeDetail data={detail} onClose={() => setDetail(null)} onSlip={downloadSlip} />
  </div>;
}

function Lifecycle({ status }: { status?: string }) { const current = status ? lifecycle.indexOf(status) : -1; return <ol aria-label="Payroll lifecycle" className="mt-6 grid grid-cols-5 gap-1">{lifecycle.map((step, index) => <li key={step} className="min-w-0"><div className={`h-1 rounded-full ${current >= index ? "bg-primary" : "bg-muted"}`} /><p className={`mt-2 text-[11px] font-medium ${current === index ? "text-foreground" : "text-muted-foreground"}`}>{labels[step]}</p></li>)}</ol>; }
function Kpi({ label, value, detail, prominent }: { label: string; value: string; detail?: string; prominent?: boolean }) { return <div className="bg-card p-4 sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 font-display text-xl font-bold tabular-nums ${prominent ? "text-primary" : "text-foreground"}`}>{value}</p>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</div>; }
function ProcessTile({ label, value, tone }: { label: string; value: string; tone: "emerald" | "blue" | "violet" }) { return <div className={`rounded-lg border p-3 payroll-process-tile payroll-process-tile--${tone}`}><p className="text-[11px] font-semibold uppercase tracking-wider">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function EmptyState({ canManageSettings }: { canManageSettings: boolean }) { return <section className="p-5 sm:p-6"><div className="rounded-2xl border border-edge bg-tint/40 p-5 sm:p-7"><Badge tone="info">First payroll</Badge><h3 className="mt-3 font-display text-xl font-semibold">Start with a controlled draft</h3><p className="mt-2 max-w-xl text-sm text-muted-foreground">Set the policy first, create a calculation draft, then review, approve, finalize, and pay. No employee payment is created at this stage.</p><ol className="mt-5 grid gap-3 sm:grid-cols-5">{["Configure policy", "Create draft", "Review", "Approve", "Finalize & pay"].map((step, index) => <li key={step} className="rounded-xl border border-edge bg-card p-3 text-sm"><span className="text-xs font-semibold text-primary">0{index + 1}</span><p className="mt-1 font-medium">{step}</p></li>)}</ol>{canManageSettings && <Button variant="outline" className="mt-5" onClick={() => { window.location.href = "/admin/payroll/configuration"; }}><Settings2 aria-hidden="true" className="h-4 w-4" />Configure payroll policy</Button>}</div></section>; }
function Register({ rows, onOpen }: { rows: Row[]; onOpen: (row: Row) => void }) { return <section className="border-b border-edge"><div className="flex flex-wrap items-end justify-between gap-3 px-5 py-4 sm:px-6"><div><h3 className="font-semibold">Payroll register</h3><p className="text-xs text-muted-foreground">Select an employee to inspect calculation inputs and documents.</p></div><Badge tone="neutral">{rows.length} employees</Badge></div><div className="w-full overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead className="border-y border-edge bg-tint/40 text-left text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="sticky left-0 z-10 bg-tint/40 px-5 py-3 sm:px-6">Employee</th><th className="px-4 py-3">Department</th><th className="px-4 py-3 text-right">Gross</th><th className="px-4 py-3 text-right">Deductions</th><th className="px-4 py-3 text-right">Net pay</th><th className="px-4 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-edge">{rows.map((row) => <tr key={row.employee.id} className="hover:bg-primary/[0.035]"><td className="sticky left-0 z-10 bg-card px-5 py-3 sm:px-6"><p className="font-medium">{person(row.employee)}</p><p className="text-xs text-muted-foreground">{row.employee.employeeNumber}</p></td><td className="px-4 py-3 text-muted-foreground">{row.employee.department?.name ?? "-"}</td><td className="px-4 py-3 text-right font-mono tabular-nums">{row.payslip ? formatMoney(row.payslip.grossEarnings) : "-"}</td><td className="px-4 py-3 text-right font-mono tabular-nums">{row.payslip ? formatMoney(row.payslip.deductions) : "-"}</td><td className="px-4 py-3 text-right font-mono font-semibold tabular-nums">{row.payslip ? formatMoney(row.payslip.netSalary) : "-"}</td><td className="px-4 py-3">{row.payslip ? <StatusPill status={row.payslip.status} /> : <Badge tone="neutral">Not calculated</Badge>}</td><td className="px-5 py-3"><Button size="sm" variant="ghost" onClick={() => onOpen(row)}>Details</Button></td></tr>)}</tbody></table></div></section>; }
function History({ history, current }: { history: Run[]; current: string }) { const router = useRouter(); const prior = history.filter((run) => run.id !== current); if (!prior.length) return null; return <section className="p-5 sm:p-6"><h3 className="font-semibold">Recent payroll runs</h3><p className="mt-1 text-xs text-muted-foreground">Drafts and completed runs in this operational scope.</p><div className="mt-3 grid gap-2">{prior.map((run) => <button key={run.id} onClick={() => router.push(`/admin/payroll/process?${new URLSearchParams({ period: run.month, run: run.id })}`)} className="flex items-center justify-between rounded-xl border border-edge px-4 py-3 text-left text-sm hover:bg-tint"><span><strong>{run.month}</strong> <span className="text-muted-foreground">{run._count.payslips} payslips · created {formatDate(new Date(run.createdAt))}</span></span><StatusPill status={run.status} /></button>)}</div></section>; }
function ReviewModal({ open, onClose, run, rows, totals, onSlip }: { open: boolean; onClose: () => void; run: Run | null; rows: Row[]; totals: { gross: number; deductions: number; net: number }; onSlip: (row: Row) => void }) { if (!run) return null; const adjustments = rows.flatMap((row) => row.payslip?.adjustments?.map((item) => ({ ...item, employee: person(row.employee) })) ?? []); const lop = rows.filter((row) => (row.payslip?.absentDeduction ?? 0) > 0); const timeline = [["Draft created", run.createdAt], ["Reviewed", run.reviewedAt], ["Approved", run.approvedAt], ["Finalized", run.finalizedAt], ["Paid", run.paidAt]].filter((entry): entry is [string, string | Date] => Boolean(entry[1])); return <Modal open={open} onClose={onClose} title={`Run review · ${run.month}`} description="Calculation summary, payroll documents, and immutable lifecycle evidence." size="xl"><div className="grid gap-3 sm:grid-cols-3"><Kpi label="Gross" value={formatMoney(totals.gross)} /><Kpi label="Deductions" value={formatMoney(totals.deductions)} /><Kpi label="Net pay" value={formatMoney(totals.net)} prominent /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section><h3 className="font-semibold">Variance, LOP & adjustments</h3><div className="mt-3 space-y-2"><p className="rounded-lg bg-tint p-3 text-sm"><strong>{lop.length}</strong> employees have loss-of-pay deductions.</p>{adjustments.length ? adjustments.map((item, index) => <p key={`${item.employee}-${index}`} className="rounded-lg border border-edge p-3 text-sm">{item.employee}: {item.label} <span className="float-right font-mono">{item.amount >= 0 ? "+" : "-"}{formatMoney(Math.abs(item.amount))}</span></p>) : <p className="text-sm text-muted-foreground">No one-off adjustments recorded.</p>}</div></section><section><h3 className="font-semibold">Audit timeline</h3><ol className="mt-3 space-y-3 border-l border-edge pl-4">{timeline.map(([label, date]) => <li key={label}><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{formatDate(new Date(date))}</p></li>)}</ol></section></div><section className="mt-6"><h3 className="font-semibold">Employee documents</h3><div className="mt-3 max-h-56 divide-y divide-edge overflow-y-auto rounded-xl border border-edge">{rows.filter((row) => row.payslip).map((row) => <div key={row.employee.id} className="flex items-center justify-between gap-3 px-3 py-2"><span className="text-sm">{person(row.employee)}</span><Button size="sm" variant="ghost" onClick={() => onSlip(row)}><FileArchive aria-hidden="true" className="h-3.5 w-3.5" />Payslip</Button></div>)}</div></section><div className="mt-5 rounded-xl border border-amber-400/25 bg-amber-500/[0.06] p-3 text-xs text-amber-200">Compliance exports are intentionally not filing-ready. Validate the applicable statutory rules before filing any output.</div></Modal>; }
function EmployeeDetail({ data, onClose, onSlip }: { data: Row | null; onClose: () => void; onSlip: (row: Row) => void }) { if (!data) return null; const p = data.payslip; return <Modal open={Boolean(data)} onClose={onClose} title={person(data.employee)} description={`${data.employee.employeeNumber} · ${data.employee.department?.name ?? "No department"}`} size="md">{p ? <div className="space-y-4"><div className="grid grid-cols-3 gap-2"><Kpi label="Gross" value={formatMoney(p.grossEarnings)} /><Kpi label="Deductions" value={formatMoney(p.deductions)} /><Kpi label="Net" value={formatMoney(p.netSalary)} prominent /></div><div className="rounded-xl bg-tint p-3 text-sm"><p>{p.presentDays} present · {p.absentDays} absent · {p.lateDays} late · {p.halfDays} half-days</p>{(p.absentDeduction ?? 0) > 0 && <p className="mt-1 text-muted-foreground">Loss of pay: {formatMoney(p.absentDeduction ?? 0)}</p>}</div>{p.adjustments?.length ? <div><h3 className="text-sm font-semibold">Adjustments</h3>{p.adjustments.map((item, index) => <p key={index} className="mt-1 text-sm text-muted-foreground">{item.label}: {formatMoney(item.amount)}</p>)}</div> : null}<Button variant="outline" className="w-full" onClick={() => onSlip(data)}><Download aria-hidden="true" className="h-4 w-4" />Download payslip</Button></div> : <div className="rounded-xl bg-tint p-4 text-sm text-muted-foreground">No payroll calculation exists for this employee in this period. Legacy payslips are documents only and are not exposed as active run controls.</div>}</Modal>; }
