"use client";

import { useRouter } from "next/navigation";
import { ArrowRightLeft, FileWarning } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney } from "@/lib/utils";

type Comparison = { totals: { grossDelta: number; deductionsDelta: number; netDelta: number }; rows: { employeeId: string; name: string; grossDelta: number; deductionsDelta: number; netDelta: number; reference: unknown; current: unknown }[] };
export function PayrollVariance({ reference, current, locationId, locations, referenceRun, currentRun, comparison }: { reference: string; current: string; locationId: string | null; locations: { id: string; name: string }[]; referenceRun: { status: string; count: number } | null; currentRun: { status: string; count: number } | null; comparison: Comparison | null }) {
  const router = useRouter();
  const change = (next: Partial<{ reference: string; current: string; location: string }>) => { const query = new URLSearchParams({ reference: next.reference ?? reference, current: next.current ?? current }); const location = next.location ?? locationId ?? ''; if (location) query.set('location', location); router.push(`/admin/payroll/variance?${query}`); };
  return <main className="payroll-canvas animate-fade-up"><header className="payroll-header"><div><p className="payroll-eyebrow">PeopleNexa payroll</p><h1>Payroll variance report</h1><p>Run-scoped financial comparison. Only finalized or paid payroll is included.</p></div></header><section className="payroll-filter"><label>Reference period<input type="month" value={reference} onChange={(event) => change({ reference: event.target.value })} /></label><ArrowRightLeft aria-hidden="true" className="mt-5 hidden h-5 w-5 text-muted-foreground md:block" /><label>Current period<input type="month" value={current} onChange={(event) => change({ current: event.target.value })} /></label><label>Location<select value={locationId ?? ''} onChange={(event) => change({ location: event.target.value })}><option value="">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><Button variant="outline" onClick={() => change({})}>Compare</Button></section>{!comparison ? <section className="payroll-empty"><FileWarning aria-hidden="true" className="h-8 w-8 text-amber-400" /><div><h2>Comparison unavailable</h2><p>{!referenceRun && !currentRun ? 'Neither selected period has finalized or paid payroll in this scope.' : !referenceRun ? 'The reference period has no finalized or paid payroll in this scope.' : 'The current period has no finalized or paid payroll in this scope.'} Draft and in-progress runs are not treated as financial history.</p></div></section> : <><section className="payroll-kpis"><Metric label="Gross variance" value={comparison.totals.grossDelta} /><Metric label="Deductions variance" value={comparison.totals.deductionsDelta} /><Metric label="Net-pay variance" value={comparison.totals.netDelta} /><Metric label="Employees compared" value={comparison.rows.length} /></section><section className="payroll-card overflow-x-auto"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><h2>Employee deltas</h2><p>{referenceRun?.count} reference payslips ({referenceRun?.status}) to {currentRun?.count} current payslips ({currentRun?.status}).</p></div></div><table className="payroll-table"><thead><tr><th>Employee</th><th className="text-right">Gross delta</th><th className="text-right">Deductions delta</th><th className="text-right">Net-pay delta</th></tr></thead><tbody>{comparison.rows.sort((a, b) => Math.abs(b.netDelta) - Math.abs(a.netDelta)).map((row) => <tr key={row.employeeId}><td>{row.name}</td><td className="text-right tnum">{signed(row.grossDelta)}</td><td className="text-right tnum">{signed(row.deductionsDelta)}</td><td className="text-right tnum font-semibold">{signed(row.netDelta)}</td></tr>)}</tbody></table></section></>}</main>;
}
function signed(value: number) { return `${value > 0 ? '+' : value < 0 ? '-' : ''}${formatMoney(Math.abs(value))}`; }
function Metric({ label, value }: { label: string; value: number }) { return <article className="payroll-metric payroll-metric--slate"><p>{label}</p><strong className="tnum">{typeof value === 'number' && label !== 'Employees compared' ? signed(value) : value}</strong></article>; }
