import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { IdCardPreviewSide } from "@/app/(portal)/admin/id-cards/id-card-generator";
import { idCardTemplate } from "@/lib/configuration";
import { ID_CARD_ARTBOARD, ID_CARD_LAYOUT, ID_CARD_SIZE, idCardDetails, idCardFieldsHeight } from "@/lib/id-card-content";

const fields = idCardDetails({ employeeNumber: "EMP-001", firstName: "Ada", lastName: "Lovelace", position: "Engineer", joiningDate: "2020-01-02", phone: "1234567890", profile: { bloodGroup: "O+" } });
const fieldsHeight = idCardFieldsHeight();
assert.equal(ID_CARD_ARTBOARD.width / ID_CARD_ARTBOARD.height, 53.98 / 85.6);
assert.equal(ID_CARD_SIZE.widthPt, 153.01417322834646);
assert.equal(ID_CARD_SIZE.heightPt, 242.64566929133858);
assert.equal(fields.length, 8);
assert.equal(new Set(fields.map(([label]) => label)).size, fields.length);
assert.ok(fields.every(([, value]) => value.length > 0));
assert.ok(ID_CARD_LAYOUT.photo.y + ID_CARD_LAYOUT.photo.height < ID_CARD_LAYOUT.fields.y);
assert.ok(Math.abs(ID_CARD_LAYOUT.fields.height - fieldsHeight) < Number.EPSILON);
assert.ok(ID_CARD_LAYOUT.fields.y + ID_CARD_LAYOUT.fields.height <= ID_CARD_LAYOUT.footer.y);
assert.equal(ID_CARD_LAYOUT.fields.overflow, "ellipsis");
assert.equal(ID_CARD_LAYOUT.background.fit, "cover");
assert.ok(ID_CARD_LAYOUT.frontContentPanel.y >= ID_CARD_LAYOUT.header.y + ID_CARD_LAYOUT.header.height);
assert.ok(ID_CARD_LAYOUT.frontContentPanel.y + ID_CARD_LAYOUT.frontContentPanel.height <= ID_CARD_LAYOUT.footer.y + Number.EPSILON);
assert.ok(ID_CARD_LAYOUT.photo.y >= ID_CARD_LAYOUT.frontContentPanel.y && ID_CARD_LAYOUT.photo.y + ID_CARD_LAYOUT.photo.height <= ID_CARD_LAYOUT.frontContentPanel.y + ID_CARD_LAYOUT.frontContentPanel.height);
assert.ok(ID_CARD_LAYOUT.fields.y >= ID_CARD_LAYOUT.frontContentPanel.y && ID_CARD_LAYOUT.fields.y + ID_CARD_LAYOUT.fields.height <= ID_CARD_LAYOUT.frontContentPanel.y + ID_CARD_LAYOUT.frontContentPanel.height);
assert.equal(idCardTemplate({ frontBackgroundUrl: "https://cdn.example.com/front.png", backBackgroundUrl: "https://cdn.example.com/back.png" })?.frontContentPanel, "preserve", "legacy templates preserve their supplied artwork");
assert.equal(idCardTemplate({ frontBackgroundUrl: "https://cdn.example.com/front.png", backBackgroundUrl: "https://cdn.example.com/back.png", frontContentPanel: "preserve" })?.frontContentPanel, "preserve");
const preview = renderToStaticMarkup(createElement(IdCardPreviewSide, { title: "Front", employee: { id: "employee-1", employeeNumber: "EMP-001", deviceCode: "DEVICE-001", firstName: "Ada", lastName: "Lovelace", position: "Engineer", joiningDate: "2020-01-02", phone: "1234567890", profilePicture: null, profile: { bloodGroup: "O+" } }, branding: null, template: null, front: true, validTill: "2028-01-02" }));
assert.match(preview, /data-testid="id-card-preview-canvas"[^>]*aspect-ratio:0\.630607/, "preview canvas uses the exact CR80 aspect ratio");
assert.match(preview, /data-testid="id-card-preview-canvas"[^>]*overflow:hidden/, "preview canvas clips only content that exceeds its CR80 bounds");
assert.match(preview, /data-testid="id-card-artwork"[^>]*object-fit:contain/, "preview artwork is uniformly contained instead of cropped");
assert.equal((preview.match(/data-testid="id-card-details"/g) ?? []).length, 1, "preview has one dynamic text layer");
assert.equal((preview.match(/data-testid="id-card-detail-row"/g) ?? []).length, fields.length, "preview renders each dynamic employee row once");
assert.match(preview, /data-testid="id-card-content-panel"[^>]*top:22%[^>]*height:63%/, "preview safe panel uses the shared normalized PDF bounds");
console.log("ID-card layout geometry tests passed");
