import assert from "node:assert/strict";
import { automaticShiftPolicy, DEFAULT_AUTOMATIC_SHIFT_POLICY, automaticShiftWindow, detectAutomaticShift } from "../lib/automatic-shifts";
import { parseIST } from "../lib/ist";
import { prisma } from "../lib/prisma";
import { applyAutomaticShiftsToday } from "../lib/apply-automatic-shifts";
import { attendanceDayForPunch, shiftForEmployeeDay, reconcileEmployeeDay } from "../lib/reconcile";

async function main() {
const ist = (s: string) => parseIST(s)!;
const day = ist("2026-10-06 00:00:00");
const morning = { id: "morning-id", startTime: "08:00", endTime: "18:00", isNightShift: false, graceMinutes: 15 };
const evening = { id: "evening-id", startTime: "20:00", endTime: "06:00", isNightShift: true, graceMinutes: 15 };
const shifts = [morning, evening];
const policy = { ...DEFAULT_AUTOMATIC_SHIFT_POLICY, enabled: true, shiftIds: shifts.map((s) => s.id) };
assert.equal(detectAutomaticShift(day, ist("2026-10-06 07:05:00"), shifts, policy)?.id, morning.id);
assert.equal(detectAutomaticShift(day, ist("2026-10-06 19:30:00"), shifts, policy)?.id, evening.id);
assert.equal(detectAutomaticShift(day, ist("2026-10-06 15:00:00"), shifts, policy), null, "outside the saved matching windows is never guessed");
assert.equal(detectAutomaticShift(day, ist("2026-10-06 07:00:00"), [{ ...morning, startTime: "10:00" }], { ...policy, earlyMinutes: 60 }), null, "changed saved timings are used");
assert.equal(automaticShiftWindow(day, evening, policy).end.toISOString(), ist("2026-10-07 08:00:00").toISOString());
assert.equal(detectAutomaticShift(day, ist("2026-10-06 14:00:00"), shifts, { ...policy, earlyMinutes: 720, lateMinutes: 720 }), null, "equidistant starts are ambiguous");
assert.equal(automaticShiftPolicy({ ...policy, shiftIds: [morning.id] }), null);
assert.equal(automaticShiftPolicy({ ...policy, earlyMinutes: -1 }), null);

// Exercise the production resolution/reconciliation paths with an in-memory
// database boundary. No production data or external database is touched.
let branch = "configured";
let roster: unknown = null;
let prior: unknown = null;
let current: unknown = null;
let hint = "out";
let punches: any[] = [];
let saved: any;
(prisma.configurationRecord as any).findFirst = async (args: any) => args.where.scopeKey === "branch:configured" ? { payload: policy } : null;
(prisma.shift as any).findMany = async () => shifts;
(prisma.shift as any).findUnique = async () => morning;
(prisma.rosterAssignment as any).findUnique = async () => roster;
(prisma.attendance as any).findUnique = async (args: any) => args.where.employeeId_date.date.getTime() === day.getTime() ? current : prior;
(prisma.punch as any).findFirst = async (args: any) => ({ inOutHint: punches.find((p) => p.punchTime.getTime() === args.where.punchTime.getTime())?.inOutHint ?? hint });
(prisma.punch as any).findMany = async (args: any) => punches.filter((p) => p.punchTime >= args.where.punchTime.gte && p.punchTime < args.where.punchTime.lt && (args.where.inOutHint?.not !== p.inOutHint));
(prisma.device as any).findMany = async () => [];
(prisma.realtimeDevice as any).findMany = async () => [];
(prisma.branch as any).findUnique = async () => null;
(prisma.attendance as any).create = async (args: any) => { saved = args.data; return { id: "attendance", ...args.data }; };
(prisma.attendance as any).update = async (args: any) => { saved = args.data; return { id: "attendance", ...args.data }; };
const employee = () => ({ id: "employee", tenantId: "tenant", branchId: branch, shiftId: null });
const punch = (s: string, type = "in") => ({ id: s, punchTime: ist(s), inOutHint: type, employeeId: "employee", tenantId: "tenant", deviceId: null, realtimeDeviceId: null, source: "device", authStatus: "auto" });
branch = "other";
assert.equal(await shiftForEmployeeDay(employee(), day), null, "unconfigured branches retain their default resolution");
branch = "configured";
punches = [punch("2026-10-06 19:30:00")];
assert.equal((await shiftForEmployeeDay(employee(), day))?.id, evening.id);
roster = { shift: morning, shiftId: morning.id };
assert.equal((await shiftForEmployeeDay(employee(), day))?.id, morning.id, "explicit roster wins");
roster = null;
prior = { shiftId: evening.id, punchInTime: ist("2026-10-05 20:00:00") };
hint = "out";
assert.equal((await attendanceDayForPunch(employee(), ist("2026-10-06 06:00:00"))).toISOString(), ist("2026-10-05 00:00:00").toISOString());
hint = "in";
assert.equal((await attendanceDayForPunch(employee(), ist("2026-10-06 07:00:00"))).toISOString(), day.toISOString(), "a morning IN after a night shift begins a new workday");
punches = [punch("2026-10-06 06:00:00", "unknown"), punch("2026-10-06 07:00:00")];
assert.equal((await shiftForEmployeeDay(employee(), day))?.id, morning.id, "prior-night unknown OUT cannot choose today's shift");
prior = null;
punches = [punch("2026-10-06 19:30:00"), punch("2026-10-07 06:00:00", "out")];
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day);
assert.equal(saved.shiftId, evening.id, "selected shift is persisted on attendance for reports and payroll");
assert.equal(saved.punchInTime.toISOString(), punches[0].punchTime.toISOString());
assert.equal(saved.punchOutTime.toISOString(), punches[1].punchTime.toISOString(), "overnight OUT stays paired with preceding IN");
punches.push(punch("2026-10-07 07:00:00"));
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day);
assert.equal(saved.punchOutTime.toISOString(), punches[1].punchTime.toISOString(), "next morning IN is excluded from the overnight window");
prior = { shiftId: evening.id, punchInTime: ist("2026-10-05 20:00:00") };
punches = [punch("2026-10-06 06:00:00", "out"), punch("2026-10-06 07:00:00"), punch("2026-10-06 18:00:00", "out")];
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day);
assert.equal(saved.punchInTime.toISOString(), punches[1].punchTime.toISOString(), "previous night OUT is excluded from the morning window");
prior = null;
punches = [punch("2026-10-06 19:30:00"), punch("2026-10-07 06:00:00", "out")];
current = { id: "attendance", shiftId: evening.id, punchInTime: punches[0].punchTime, finalized: true, punchOutTime: punches[1].punchTime, status: "present", lateMinutes: 0, reviewStatus: null };
saved = null;
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day);
assert.equal(saved, null, "ingestion preserves finalized attendance");
current = null;
let updateFilter: any;
let updateData: any;
(prisma.attendance as any).findMany = async (args: any) => {
  assert.equal(args.where.tenantId, "tenant");
  assert.equal(args.where.employee.branchId, "configured");
  assert.equal(args.where.finalized, false);
  assert.equal(args.where.shiftId, null);
  assert.equal(args.where.date.getTime(), day.getTime());
  return [{ id: "attendance", employee: employee() }];
};
(prisma.attendance as any).updateMany = async (args: any) => { updateFilter = args.where; updateData = args.data; return { count: 1 }; };
assert.equal(await applyAutomaticShiftsToday("tenant", "configured", { ...policy, enabled: false }, day), 0);
assert.equal(await applyAutomaticShiftsToday("tenant", "configured", policy, day), 1, "saving can fill a missing shift using existing IN punches");
assert.deepEqual(updateData, { shiftId: evening.id }, "backfill changes only shift, preserving status and payroll inputs");
assert.equal(updateFilter.finalized, false, "concurrent finalization remains protected at write time");
assert.equal(updateFilter.shiftId, null, "an existing selected shift cannot be overwritten");
assert.equal(updateFilter.employee.branchId, "configured");
roster = { shift: { ...morning, singlePunchHalfDay: true }, shiftId: morning.id };
saved = {};
punches = [punch("2026-10-06 08:00:00")];
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day, { finalize: true });
assert.equal(saved.status, "half_day", "saved shift rule applies half-day absence to one punch");
assert.equal(saved.reviewStatus, null, "configured single-punch treatment does not require review");
assert.equal(saved.punchOutTime, null, "half-day treatment never fabricates OUT");
assert.equal(saved.overtimeMinutes, 0);
punches = [punch("2026-10-06 18:00:00", "out")];
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day, { finalize: true });
assert.equal(saved.status, "half_day", "OUT-only single punch follows the same rule");
assert.equal(saved.punchInTime, null, "OUT-only attendance never fabricates IN");
assert.equal(saved.reviewStatus, null);
roster = { shift: { ...morning, singlePunchHalfDay: false }, shiftId: morning.id };
punches = [punch("2026-10-06 08:00:00")];
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day, { finalize: true });
assert.equal(saved.reviewStatus, "missed_punch", "unchecked rule retains existing treatment");
branch = "other";
roster = null;
(prisma.configurationRecord as any).findFirst = async (args: any) => args.where.kind === "unassigned_shift_attendance" && args.where.tenantId === "tenant" ? { payload: { singlePunchHalfDay: true } } : null;
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day, { finalize: true });
assert.equal(saved.status, "half_day", "workspace checkbox covers employees without any shift");
assert.equal(saved.shiftId, null, "unassigned policy does not invent a shift");
assert.equal(saved.reviewStatus, null);
assert.equal(saved.punchOutTime, null);
roster = { shift: { ...morning, singlePunchHalfDay: false }, shiftId: morning.id };
await reconcileEmployeeDay({ id: "tenant", config: null }, employee(), day, { finalize: true });
assert.equal(saved.reviewStatus, "missed_punch", "unassigned fallback cannot override an assigned shift's unchecked rule");
console.log("automatic shift tests passed");
}
main().catch((e) => { console.error(e); process.exitCode = 1; }).finally(() => prisma.$disconnect());
